package com.wwwescape.pixelebookreader.ui.screens.history

import android.app.Application
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.viewModelScope
import com.wwwescape.pixelebookreader.data.history.HistoryEntry
import com.wwwescape.pixelebookreader.data.history.HistoryRepository
import com.wwwescape.pixelebookreader.data.history.HistoryWithBook
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.combine
import kotlinx.coroutines.flow.stateIn
import kotlinx.coroutines.launch
import java.time.Instant
import java.time.ZoneId

class HistoryViewModel(application: Application) : AndroidViewModel(application) {

    private val searchQuery = MutableStateFlow("")
    private val _lastDeleted = MutableStateFlow<HistoryWithBook?>(null)
    val lastDeleted: StateFlow<HistoryWithBook?> = _lastDeleted.asStateFlow()

    val uiState: StateFlow<HistoryUiState> = combine(
        HistoryRepository.getAllHistoryWithBooks(application),
        searchQuery,
    ) { all, query ->
        val filtered = all.filter {
            query.isBlank() || it.title.contains(query, ignoreCase = true) || it.author?.contains(query, ignoreCase = true) == true
        }
        val sections = filtered
            .groupBy { entry -> Instant.ofEpochMilli(entry.openedAt).atZone(ZoneId.systemDefault()).toLocalDate() }
            .toSortedMap(compareByDescending { it })
            .map { (date, entries) -> HistorySection(date, entries) }
        HistoryUiState(sections = sections, searchQuery = query, isEmpty = all.isEmpty())
    }.stateIn(viewModelScope, SharingStarted.WhileSubscribed(5_000), HistoryUiState())

    fun setSearchQuery(query: String) {
        searchQuery.value = query
    }

    fun deleteEntry(entry: HistoryWithBook) = viewModelScope.launch {
        HistoryRepository.deleteEntry(getApplication(), HistoryEntry(id = entry.historyId, bookId = entry.bookId, openedAt = entry.openedAt))
        _lastDeleted.value = entry
    }

    /** Re-inserts with the original [HistoryWithBook.openedAt] rather than "now", so an undone
     * delete looks exactly like it was never deleted — it necessarily gets a new row id since
     * that's autogenerated, but nothing user-visible reflects that. */
    fun undoDelete() = viewModelScope.launch {
        val entry = _lastDeleted.value ?: return@launch
        HistoryRepository.recordOpen(getApplication(), entry.bookId, entry.openedAt)
        _lastDeleted.value = null
    }

    fun consumeUndoState() {
        _lastDeleted.value = null
    }

    fun deleteAll() = viewModelScope.launch {
        HistoryRepository.deleteAllHistory(getApplication())
    }
}
